name: tarot
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  avatar_glow:
  bordered_text: ^2.0.0
  cached_network_image:
  carousel_slider:
  cupertino_icons:

  flutter:
    sdk: flutter

  flutter_launcher_icons:
  flutter_native_splash:
  flutter_polyline_points:
  font_awesome_flutter:

  freezed_annotation:

  get:
  google_fonts: ^3.0.1
  google_maps_flutter:

  hooks_riverpod:

  http:
  intl:

  json_annotation:

  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  uuid:

dev_dependencies:

  build_runner:

  flutter_lints:

  flutter_test:
    sdk: flutter

  freezed:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/image/

flutter_native_splash:
  image: "assets/image/tarotcard.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launchericon.JPG"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/image/launchericon.JPG"
